name: Somnus Lab 24-7
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instalar FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Descargar Video
        run: |
          # REEMPLAZA EL LINK ABAJO POR TU DROPBOX TERMINADO EN dl=1
          wget -O video.mp4 https://www.dropbox.com/scl/fi/kfh4ztijoyujkao3bj170/video.mp4?rlkey=h8tn0dc61qtrkmszjsknwlc5i&st=hgdo6rg5&dl=1

      - name: Transmitir
        run: |
          ffmpeg -re -stream_loop -1 -i video.mp4 -t 21900 -c:v libx264 -preset veryfast -b:v 2500k -maxrate 2500k -bufsize 5000k -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 44100 -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_KEY }}"
